package com.vber.sp_fae_client_orders_oauth2.config;

import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;

//curl -i http://localhost:9090/api/v1/clientorders

//export TOKEN=$(curl -H "Content-Type: application/x-www-form-urlencoded" \
//-d "client_id=fae-client-orders-oauth2" \
//-d "username=user1" \
//-d "password=user1" \
//-d "grant_type=password" \
//-X POST http://localhost:8180/auth/realms/fae-client-orders-oauth2/protocol/openid-connect/token | jq -r .access_token)
//$echo $TOKEN
//curl -H "Content-Type: application/x-www-form-urlencoded" -d "client_id=fae-client-orders-oauth2" -d "username=user1" -d "password=user1" -d "grant_type=password" -X POST http://localhost:8180/auth/realms/fae-client-orders-oauth2/protocol/openid-connect/token | jq -r .access_token

//{"access_token":"eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIyTG5udmxma25pWERUbG1CeG9jRmZFUzlPNzFkRUFKSHBwTzBUbUVadXNVIn0.eyJleHAiOjE2NDA4MDIwODYsImlhdCI6MTY0MDgwMTc4NiwianRpIjoiMjJlNzc5N2UtOGRiMS00NWM2LWE1MmEtOTY5MmIxZTRmYjA5IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MTgwL2F1dGgvcmVhbG1zL2ZhZS1jbGllbnQtb3JkZXJzLW9hdXRoMiIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiJmZTc3YzMwNi0wMTFjLTQwMjYtYmY3Yy1kNGI2NWNlNzRlMjciLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJmYWUtY2xpZW50LW9yZGVycy1vYXV0aDIiLCJzZXNzaW9uX3N0YXRlIjoiMzEzMzhjOWMtN2EwYi00OTRjLWE4OWQtMjJiNTZmMzBjYjg4IiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6WyIqIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLWZhZS1jbGllbnQtb3JkZXJzLW9hdXRoMiIsIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iLCJhcHAtdXNlciJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoiZW1haWwgZmFlLWNsaWVudC1vcmRlcnMtb2F1dGgyIHByb2ZpbGUiLCJzaWQiOiIzMTMzOGM5Yy03YTBiLTQ5NGMtYTg5ZC0yMmI1NmYzMGNiODgiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicHJlZmVycmVkX3VzZXJuYW1lIjoidXNlcjEifQ.XdqI3B0tX2zwlHVHth5dVTGM2mtc8UCQROGMdTKy1pjaFI6FcM7PAHCRNA3RaT2zKqJhRz65MuQVcFW_dd3DU_g6GkG_Wa8lf9-0mmQyYtZFteDPH2KvthbTYaLthNvT6GvG_PWB4OmwcaH5R3-ggizTLeydtKD--cyhOzdsdDznFTb-3C4FeMTOmRXDASSsPR866VLEabEd8q-FYbnZSmQHQ08zhlRlHMKqaYMbVAC7evU-C0Ly2RNU3trIo97Pcl-aeh1qt7HZBum6Rp4hO8tEyxmmx_fkbHzW7ncijBCmZtt9q_RGqjVdECu79J105c0woueSfV8ofwnuG49l0Q","expires_in":300,"refresh_expires_in":1800,"refresh_token":"eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI3ZmZkNjI2Ny03YjQzLTRkZDctYmE5MS1lYzg0OTJhY2YyZjgifQ.eyJleHAiOjE2NDA4MDM1ODYsImlhdCI6MTY0MDgwMTc4NiwianRpIjoiYWNhMGZhNWUtMTg4Ny00NWYyLWJmOWMtNGFhZjY2NjlmYzZmIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MTgwL2F1dGgvcmVhbG1zL2ZhZS1jbGllbnQtb3JkZXJzLW9hdXRoMiIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODE4MC9hdXRoL3JlYWxtcy9mYWUtY2xpZW50LW9yZGVycy1vYXV0aDIiLCJzdWIiOiJmZTc3YzMwNi0wMTFjLTQwMjYtYmY3Yy1kNGI2NWNlNzRlMjciLCJ0eXAiOiJSZWZyZXNoIiwiYXpwIjoiZmFlLWNsaWVudC1vcmRlcnMtb2F1dGgyIiwic2Vzc2lvbl9zdGF0ZSI6IjMxMzM4YzljLTdhMGItNDk0Yy1hODlkLTIyYjU2ZjMwY2I4OCIsInNjb3BlIjoiZW1haWwgZmFlLWNsaWVudC1vcmRlcnMtb2F1dGgyIHByb2ZpbGUiLCJzaWQiOiIzMTMzOGM5Yy03YTBiLTQ5NGMtYTg5ZC0yMmI1NmYzMGNiODgifQ.O0pimBE1xqHek6IQ0ADuOVtjaB99DiagHBIxfrcvDag","token_type":"Bearer","not-before-policy":0,"session_state":"31338c9c-7a0b-494c-a89d-22b56f30cb88","scope":"email fae-client-orders-oauth2 profile"}

//eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIyTG5udmxma25pWERUbG1CeG9jRmZFUzlPNzFkRUFKSHBwTzBUbUVadXNVIn0.eyJleHAiOjE2NDA4MDIwODYsImlhdCI6MTY0MDgwMTc4NiwianRpIjoiMjJlNzc5N2UtOGRiMS00NWM2LWE1MmEtOTY5MmIxZTRmYjA5IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MTgwL2F1dGgvcmVhbG1zL2ZhZS1jbGllbnQtb3JkZXJzLW9hdXRoMiIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiJmZTc3YzMwNi0wMTFjLTQwMjYtYmY3Yy1kNGI2NWNlNzRlMjciLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJmYWUtY2xpZW50LW9yZGVycy1vYXV0aDIiLCJzZXNzaW9uX3N0YXRlIjoiMzEzMzhjOWMtN2EwYi00OTRjLWE4OWQtMjJiNTZmMzBjYjg4IiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6WyIqIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLWZhZS1jbGllbnQtb3JkZXJzLW9hdXRoMiIsIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iLCJhcHAtdXNlciJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoiZW1haWwgZmFlLWNsaWVudC1vcmRlcnMtb2F1dGgyIHByb2ZpbGUiLCJzaWQiOiIzMTMzOGM5Yy03YTBiLTQ5NGMtYTg5ZC0yMmI1NmYzMGNiODgiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicHJlZmVycmVkX3VzZXJuYW1lIjoidXNlcjEifQ.XdqI3B0tX2zwlHVHth5dVTGM2mtc8UCQROGMdTKy1pjaFI6FcM7PAHCRNA3RaT2zKqJhRz65MuQVcFW_dd3DU_g6GkG_Wa8lf9-0mmQyYtZFteDPH2KvthbTYaLthNvT6GvG_PWB4OmwcaH5R3-ggizTLeydtKD--cyhOzdsdDznFTb-3C4FeMTOmRXDASSsPR866VLEabEd8q-FYbnZSmQHQ08zhlRlHMKqaYMbVAC7evU-C0Ly2RNU3trIo97Pcl-aeh1qt7HZBum6Rp4hO8tEyxmmx_fkbHzW7ncijBCmZtt9q_RGqjVdECu79J105c0woueSfV8ofwnuG49l0Q","expires_in":300,"refresh_expires_in":1800,"refresh_token":"eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI3ZmZkNjI2Ny03YjQzLTRkZDctYmE5MS1lYzg0OTJhY2YyZjgifQ.eyJleHAiOjE2NDA4MDM1ODYsImlhdCI6MTY0MDgwMTc4NiwianRpIjoiYWNhMGZhNWUtMTg4Ny00NWYyLWJmOWMtNGFhZjY2NjlmYzZmIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MTgwL2F1dGgvcmVhbG1zL2ZhZS1jbGllbnQtb3JkZXJzLW9hdXRoMiIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODE4MC9hdXRoL3JlYWxtcy9mYWUtY2xpZW50LW9yZGVycy1vYXV0aDIiLCJzdWIiOiJmZTc3YzMwNi0wMTFjLTQwMjYtYmY3Yy1kNGI2NWNlNzRlMjciLCJ0eXAiOiJSZWZyZXNoIiwiYXpwIjoiZmFlLWNsaWVudC1vcmRlcnMtb2F1dGgyIiwic2Vzc2lvbl9zdGF0ZSI6IjMxMzM4YzljLTdhMGItNDk0Yy1hODlkLTIyYjU2ZjMwY2I4OCIsInNjb3BlIjoiZW1haWwgZmFlLWNsaWVudC1vcmRlcnMtb2F1dGgyIHByb2ZpbGUiLCJzaWQiOiIzMTMzOGM5Yy03YTBiLTQ5NGMtYTg5ZC0yMmI1NmYzMGNiODgifQ.O0pimBE1xqHek6IQ0ADuOVtjaB99DiagHBIxfrcvDag
//set "ttoken=eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIyTG5udmxma25pWERUbG1CeG9jRmZFUzlPNzFkRUFKSHBwTzBUbUVadXNVIn0.eyJleHAiOjE2NDA4MDIwODYsImlhdCI6MTY0MDgwMTc4NiwianRpIjoiMjJlNzc5N2UtOGRiMS00NWM2LWE1MmEtOTY5MmIxZTRmYjA5IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MTgwL2F1dGgvcmVhbG1zL2ZhZS1jbGllbnQtb3JkZXJzLW9hdXRoMiIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiJmZTc3YzMwNi0wMTFjLTQwMjYtYmY3Yy1kNGI2NWNlNzRlMjciLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJmYWUtY2xpZW50LW9yZGVycy1vYXV0aDIiLCJzZXNzaW9uX3N0YXRlIjoiMzEzMzhjOWMtN2EwYi00OTRjLWE4OWQtMjJiNTZmMzBjYjg4IiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6WyIqIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLWZhZS1jbGllbnQtb3JkZXJzLW9hdXRoMiIsIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iLCJhcHAtdXNlciJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoiZW1haWwgZmFlLWNsaWVudC1vcmRlcnMtb2F1dGgyIHByb2ZpbGUiLCJzaWQiOiIzMTMzOGM5Yy03YTBiLTQ5NGMtYTg5ZC0yMmI1NmYzMGNiODgiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicHJlZmVycmVkX3VzZXJuYW1lIjoidXNlcjEifQ.XdqI3B0tX2zwlHVHth5dVTGM2mtc8UCQROGMdTKy1pjaFI6FcM7PAHCRNA3RaT2zKqJhRz65MuQVcFW_dd3DU_g6GkG_Wa8lf9-0mmQyYtZFteDPH2KvthbTYaLthNvT6GvG_PWB4OmwcaH5R3-ggizTLeydtKD--cyhOzdsdDznFTb-3C4FeMTOmRXDASSsPR866VLEabEd8q-FYbnZSmQHQ08zhlRlHMKqaYMbVAC7evU-C0Ly2RNU3trIo97Pcl-aeh1qt7HZBum6Rp4hO8tEyxmmx_fkbHzW7ncijBCmZtt9q_RGqjVdECu79J105c0woueSfV8ofwnuG49l0Q\",\"expires_in\":300,\"refresh_expires_in\":1800,\"refresh_token\":\"eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI3ZmZkNjI2Ny03YjQzLTRkZDctYmE5MS1lYzg0OTJhY2YyZjgifQ.eyJleHAiOjE2NDA4MDM1ODYsImlhdCI6MTY0MDgwMTc4NiwianRpIjoiYWNhMGZhNWUtMTg4Ny00NWYyLWJmOWMtNGFhZjY2NjlmYzZmIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MTgwL2F1dGgvcmVhbG1zL2ZhZS1jbGllbnQtb3JkZXJzLW9hdXRoMiIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODE4MC9hdXRoL3JlYWxtcy9mYWUtY2xpZW50LW9yZGVycy1vYXV0aDIiLCJzdWIiOiJmZTc3YzMwNi0wMTFjLTQwMjYtYmY3Yy1kNGI2NWNlNzRlMjciLCJ0eXAiOiJSZWZyZXNoIiwiYXpwIjoiZmFlLWNsaWVudC1vcmRlcnMtb2F1dGgyIiwic2Vzc2lvbl9zdGF0ZSI6IjMxMzM4YzljLTdhMGItNDk0Yy1hODlkLTIyYjU2ZjMwY2I4OCIsInNjb3BlIjoiZW1haWwgZmFlLWNsaWVudC1vcmRlcnMtb2F1dGgyIHByb2ZpbGUiLCJzaWQiOiIzMTMzOGM5Yy03YTBiLTQ5NGMtYTg5ZC0yMmI1NmYzMGNiODgifQ.O0pimBE1xqHek6IQ0ADuOVtjaB99DiagHBIxfrcvDag"
//curl -i -X GET -H "Authorization: Bearer $TOKEN" http://localhost:9090/api/v1/clientorders
//curl -i -X GET -H "Authorization: Bearer ttoken" http://localhost:9090/api/v1/clientorders
//curl -i -X GET -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIyTG5udmxma25pWERUbG1CeG9jRmZFUzlPNzFkRUFKSHBwTzBUbUVadXNVIn0.eyJleHAiOjE2NDA4MDMyNjQsImlhdCI6MTY0MDgwMjk2NCwianRpIjoiOWY4MTA3NmUtMTM1Mi00NWZiLTk0MzQtMjcwNmNhMjI4YzcyIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MTgwL2F1dGgvcmVhbG1zL2ZhZS1jbGllbnQtb3JkZXJzLW9hdXRoMiIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiJmZTc3YzMwNi0wMTFjLTQwMjYtYmY3Yy1kNGI2NWNlNzRlMjciLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJmYWUtY2xpZW50LW9yZGVycy1vYXV0aDIiLCJzZXNzaW9uX3N0YXRlIjoiNWJiZDlmMjctNjc1ZC00MWRjLWFjZmYtMDhlOTAxMTVlMzM2IiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6WyIqIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLWZhZS1jbGllbnQtb3JkZXJzLW9hdXRoMiIsIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iLCJhcHAtdXNlciJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoiZW1haWwgZmFlLWNsaWVudC1vcmRlcnMtb2F1dGgyIHByb2ZpbGUiLCJzaWQiOiI1YmJkOWYyNy02NzVkLTQxZGMtYWNmZi0wOGU5MDExNWUzMzYiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicHJlZmVycmVkX3VzZXJuYW1lIjoidXNlcjEifQ.Avew98OIN4wy4BcAKKDSGCdh2LLid-W70MHJSWyk__nds0ckYQscVAZtuhO1q_eDZk3hr06gr94lHP-RbE6bTHDwxekRo5e9Vf9AGwSPceWw1_8Ek0boSbLti6ViKvqJK4auzG8Fgd7x92oSDARHacozNFqwW8D_yzvZQBE_pGvvBWsyeKNZLb4OpK1SWY1AyJ22OG0WvXx4N57hwKjIrtAxqaazkcbTVQC5YmnoH-grJ5FIU4lEMGue8PE9BfCwE4G-5FA8KzdPHr2TVh2o_QaHAhofq2fptWJBygNAsW20aGhn9xF_depNIHDCQ5W8b8oHxAItVCVUrZ54aZquMA","expires_in":300,"refresh_expires_in":1800,"refresh_token":"eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI3ZmZkNjI2Ny03YjQzLTRkZDctYmE5MS1lYzg0OTJhY2YyZjgifQ.eyJleHAiOjE2NDA4MDQ3NjQsImlhdCI6MTY0MDgwMjk2NCwianRpIjoiNzVlZWM2NzUtMzk0NC00YzJkLWFlYzItZjJmNDE5ZmEzNGFkIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MTgwL2F1dGgvcmVhbG1zL2ZhZS1jbGllbnQtb3JkZXJzLW9hdXRoMiIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODE4MC9hdXRoL3JlYWxtcy9mYWUtY2xpZW50LW9yZGVycy1vYXV0aDIiLCJzdWIiOiJmZTc3YzMwNi0wMTFjLTQwMjYtYmY3Yy1kNGI2NWNlNzRlMjciLCJ0eXAiOiJSZWZyZXNoIiwiYXpwIjoiZmFlLWNsaWVudC1vcmRlcnMtb2F1dGgyIiwic2Vzc2lvbl9zdGF0ZSI6IjViYmQ5ZjI3LTY3NWQtNDFkYy1hY2ZmLTA4ZTkwMTE1ZTMzNiIsInNjb3BlIjoiZW1haWwgZmFlLWNsaWVudC1vcmRlcnMtb2F1dGgyIHByb2ZpbGUiLCJzaWQiOiI1YmJkOWYyNy02NzVkLTQxZGMtYWNmZi0wOGU5MDExNWUzMzYifQ.8p5vmOkATWgQNp-sTv-OmQAy92nz2BAlY8EoPK4ubNM" http://localhost:9090/api/v1/clientorders

@EnableWebSecurity
public class ResourceServerConfig extends WebSecurityConfigurerAdapter {

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http.cors().and()
                .authorizeRequests()
                .mvcMatchers("/api/v1/**")             .hasAuthority("SCOPE_fae-client-orders-oauth2")
              //.mvcMatchers("/api/v1/clientorders/**").hasAuthority("SCOPE_fae-client-orders-oauth2")
                .anyRequest().denyAll()
                .and()
                .oauth2ResourceServer()
                .jwt();
    }

}

/*
import org.keycloak.adapters.springboot.KeycloakSpringBootConfigResolver;
import org.keycloak.adapters.springsecurity.authentication.KeycloakAuthenticationProvider;
import org.keycloak.adapters.springsecurity.config.KeycloakWebSecurityConfigurerAdapter;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.config.annotation.authentication.builders.AuthenticationManagerBuilder;
import org.springframework.security.config.annotation.method.configuration.EnableGlobalMethodSecurity;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.core.authority.mapping.SimpleAuthorityMapper;
import org.springframework.security.web.authentication.session.NullAuthenticatedSessionStrategy;
import org.springframework.security.web.authentication.session.SessionAuthenticationStrategy;

@Configuration
@EnableWebSecurity
@EnableGlobalMethodSecurity(jsr250Enabled = true)
public class ResourceServerConfig extends KeycloakWebSecurityConfigurerAdapter {
  @Override
  protected void configure(HttpSecurity http) throws Exception {
    super.configure(http);
    http.cors().and()
               .authorizeRequests().anyRequest().permitAll()
             //.mvcMatchers("/api/v1/clientorders/**").hasAuthority("SCOPE_fae-client-orders-oauth2")
             //.anyRequest().denyAll()
             //.and()
             //.oauth2ResourceServer()
             //.jwt()
               ;
    http.csrf().disable();
  }
  @Autowired
  public void configureGlobal(AuthenticationManagerBuilder auth) throws Exception {
    KeycloakAuthenticationProvider keycloakAuthenticationProvider = keycloakAuthenticationProvider();
    keycloakAuthenticationProvider.setGrantedAuthoritiesMapper(new SimpleAuthorityMapper());
    auth.authenticationProvider(keycloakAuthenticationProvider);
  }
  @Bean
  @Override
  protected SessionAuthenticationStrategy sessionAuthenticationStrategy() {
    return new NullAuthenticatedSessionStrategy();
  }
  @Bean
  public org.keycloak.adapters.KeycloakConfigResolver KeycloakConfigResolver() {
    return new KeycloakSpringBootConfigResolver();
  }
}
*/